name = "artificial-intelligentsia"
compatibility_date = "2024-01-01"

pages_build_output_dir = "dist"

[build]
command = "npm ci --legacy-peer-deps && npm run build"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"
NODE_OPTIONS = "--legacy-peer-deps"

[vars]
NODE_OPTIONS = "--legacy-peer-deps"
