name = "artificial-intelligentsia"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "frontend"
watch_dir = "frontend/src"

[build.environment_variables]
NODE_VERSION = "18"
NODE_OPTIONS = "--legacy-peer-deps"

[vars]
NODE_OPTIONS = "--legacy-peer-deps"
