name = "bi-dashboard-mcp-server"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENABLED_MODULES = "serp,keywords,backlinks,domain_analytics,business_data,content_analysis,onpage,labs"
ENABLED_PROMPTS = "analyze_serp,keyword_research,competitor_analysis,technical_audit"
DATAFORSEO_FULL_RESPONSE = "true"

# Environment variables will be set via wrangler secret
# DATAFORSEO_USERNAME (set via: wrangler secret put DATAFORSEO_USERNAME)
# DATAFORSEO_PASSWORD (set via: wrangler secret put DATAFORSEO_PASSWORD)
